Rails DB/Stadium-Delivery-Rails-DB/config/routes.rb
Rails.application.routes.draw do
  resources :orderproducts
  
 
    namespace :api do
      namespace :v1 do
        mount_devise_token_auth_for 'User', at: 'auth',
  controllers: {
    sessions: 'api/v1/sessions',
    registrations: 'devise_token_auth/registrations',
    
  }
        resources :products
        resources :users
        resources :orders
    
      end

      # post "/new_orders", to: "api/v1/orders#create"
  # post "/auth/sign_in", to: "api/v1/users#create"
  # post "/auth/sign_in", to: "api/v1/devise_token_auth/sessions#create"
end
root 'pages#home'
end

Rails DB/Stadium-Delivery-Rails-DB/app/models/orderproduct.rb
class Orderproduct < ApplicationRecord
    belongs_to :order
    belongs_to :product
end

Rails DB/Stadium-Delivery-Rails-DB/app/controllers/api/v1/orderproducts_controller.rb
class OrderproductsController < ApplicationController
  before_action :set_orderproduct, only: %i[ show edit update destroy ]

  # GET /orderproducts
  def index
    @orderproducts = Orderproduct.all
  end

  # GET /orderproducts/1
  def show
  end

  # GET /orderproducts/new
  def new
    @orderproduct = Orderproduct.new
  end

  # GET /orderproducts/1/edit
  def edit
  end

  # POST /orderproducts
  def create
    @orderproduct = Orderproduct.new(orderproduct_params)

    if @orderproduct.save
      redirect_to @orderproduct, notice: "Orderproduct was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /orderproducts/1
  def update
    if @orderproduct.update(orderproduct_params)
      redirect_to @orderproduct, notice: "Orderproduct was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /orderproducts/1
  def destroy
    @orderproduct.destroy
    redirect_to orderproducts_url, notice: "Orderproduct was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_orderproduct
      @orderproduct = Orderproduct.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def orderproduct_params
      params.require(:orderproduct).permit(:order_id, :product_id)
    end
end

Rails DB/Stadium-Delivery-Rails-DB/app/helpers/orderproducts_helper.rb
module OrderproductsHelper
end

Rails DB/Stadium-Delivery-Rails-DB/app/views/orderproducts/_form.html.erb
<%= form_with(model: orderproduct) do |form| %>
  <% if orderproduct.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(orderproduct.errors.count, "error") %> prohibited this orderproduct from being saved:</h2>

      <ul>
        <% orderproduct.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :order_id, style: "display: block" %>
    <%= form.text_field :order_id %>
  </div>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.text_field :product_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Rails DB/Stadium-Delivery-Rails-DB/app/views/orderproducts/_orderproduct.html.erb
<div id="<%= dom_id orderproduct %>">
  <p>
    <strong>Order:</strong>
    <%= orderproduct.order_id %>
  </p>

  <p>
    <strong>Product:</strong>
    <%= orderproduct.product_id %>
  </p>

</div>

Rails DB/Stadium-Delivery-Rails-DB/app/views/orderproducts/edit.html.erb
<h1>Editing orderproduct</h1>

<%= render "form", orderproduct: @orderproduct %>

<br>

<div>
  <%= link_to "Show this orderproduct", @orderproduct %> |
  <%= link_to "Back to orderproducts", orderproducts_path %>
</div>

Rails DB/Stadium-Delivery-Rails-DB/app/views/orderproducts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Orderproducts</h1>

<div id="orderproducts">
  <% @orderproducts.each do |orderproduct| %>
    <%= render orderproduct %>
    <p>
      <%= link_to "Show this orderproduct", orderproduct %>
    </p>
  <% end %>
</div>

<%= link_to "New orderproduct", new_orderproduct_path %>

Rails DB/Stadium-Delivery-Rails-DB/app/views/orderproducts/new.html.erb
<h1>New orderproduct</h1>

<%= render "form", orderproduct: @orderproduct %>

<br>

<div>
  <%= link_to "Back to orderproducts", orderproducts_path %>
</div>

Rails DB/Stadium-Delivery-Rails-DB/app/views/orderproducts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @orderproduct %>

<div>
  <%= link_to "Edit this orderproduct", edit_orderproduct_path(@orderproduct) %> |
  <%= link_to "Back to orderproducts", orderproducts_path %>

  <%= button_to "Destroy this orderproduct", @orderproduct, method: :delete %>
</div>